Update pre-commit script

diff --git a/install/pre-commit b/install/pre-commit
--- a/install/pre-commit
+++ b/install/pre-commit
@@ -14,13 +14,13 @@ then
 fi
 SFILES=${SFILES:-$STAGED_FILES_CMD}
 
-echo "Checking PHP Lint..."
+printf "Checking PHP Lint...\n"
 for FILE in $SFILES
 do
 	php -l -d display_errors=0 $PROJECT/$FILE
 	if [ $? != 0 ]
 	then
-		echo "Fix the error (php) before commit."
+		printf "Fix the error (php) before commit.\n"
 		exit 1
 	fi
 	FILES="$FILES $PROJECT/$FILE"
@@ -28,13 +28,18 @@ done
 
 if [ "$FILES" != "" ]
 then
-	echo "Running Code Sniffer..."
-	phpcs --encoding=utf-8 $FILES
-	if [ $? != 0 ]
-	then
-		echo "Fix the error (phpcs) before commit."
-#		exit 1
-	fi
+    if command -v phpcs > /dev/null 2>&1; then
+        printf "Running Code Sniffer...\n"
+        phpcs --encoding=utf-8 $FILES
+        if [ $? != 0 ]
+        then
+            printf "Fix the error (phpcs) before commit.\n"
+            exit 1
+        fi
+    else
+        printf "Recommand installing phpcs.\n"
+        exit 0
+    fi
 fi
 
 exit $?
